#!/usr/bin/env bash

shopt -s extglob 

declare -r app_name="${0##*/}"
declare coursier=()

declare -r scalaVersion3="3.0.0"

function getLatestVersion() {
  tmp1="$(curl -sL $1)"
  tmp2="${tmp1##*<latest>}"
  latestVersion="${tmp2%%</latest>*}"
  echo "$latestVersion"
}

function getMileStoneVersion() {
    case "$1" in
      -3.M[1-3])
        m="${1:3:5}"
        echo "$scalaVersion3-$m"
      ;;
    esac
}

mileStoneVersion="$(getMileStoneVersion "$1")" && shift

groupId="org.scala-lang"
artifactId="scala3-staging_$mileStoneVersion"
repository="https://repo1.maven.org/maven2/org/scala-lang/scala3-staging_$mileStoneVersion"
version="$(getLatestVersion "$repository/maven-metadata.xml")"

# https://repo1.maven.org/maven2/org/scala-lang/scala3-staging_3.0.0-M2/
coursier+=("-r=$repository")

coursier+=("$groupId:$artifactId:$version")

case "$app_name" in 
  scala)
    cs launch "${coursier[@]}" -M dotty.tools.repl.Main -- -usejavacp "$@" 
    ;;
  scalac)
    cs launch "${coursier[@]}" -M dotty.tools.dotc.Main -- -usejavacp "$@"
    ;;
esac
